### ISSUE TITLE
Github link is wrong

### ISSUE THREAD

**Issue by PonteIneptique** [perseids-project/greek-conjugator-js#1]
When clicking on the flag, the link is https://github.com/perseids-project/conjugator-js/issues , same for github.
It should read greek-conjugator-js

**Comment by PonteIneptique** [comment]
Hurrah otherwise !

**Comment by zfletch** [comment]
@PonteIneptique thank you for pointing this out! I've updated it in https://github.com/perseids-project/greek-conjugator-js/commit/50d05d01c445f89e3fad7069a7d69385338ffb3a and reployed.
